### ISSUE TITLE
Wrong links in README

### ISSUE THREAD

**Issue by Eloitor** [ask0ldd/OsspitaUI#2]
Hi,

Thanks for this promising UI!

I noticed that the links in the readme for Llama 3.2:3b and Mistral Nemo:12b are wrong.

**Comment by ask0ldd** [comment]
Hi,

Thank you very much for your kind words and valuable help! :D

I’m not sure how I made such a silly mistake.

The links have been updated, and the changes will be pushed soon!

Have a nice evening!
