### ISSUE TITLE
Can't reach Ollama endpoints.

### ISSUE THREAD

**Issue by RYG81** [ask0ldd/OsspitaUI#3]
hi
first of all your tool looks far better than chatgpt

I want to actually try this and so i cloned repo and installed all things. But I am getting these errors

5:41:00 PM [vite] http proxy error: /api/tags
Error: connect ECONNREFUSED ::1:11434
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
5:41:00 PM [vite] http proxy error: /api/tags
Error: connect ECONNREFUSED ::1:11434
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) (x2)
5:41:49 PM [vite] http proxy error: /api/ps
Error: connect ECONNREFUSED ::1:11434
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
5:41:49 PM [vite] http proxy error: /api/tags
Error: connect ECONNREFUSED ::1:11434
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
5:41:49 PM [vite] http proxy error: /api/ps
Error: connect ECONNREFUSED ::1:11434
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
5:41:49 PM [vite] http proxy error: /api/tags
Error: connect ECONNREFUSED ::1:11434
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)

can you help with this?

**Comment by RYG81** [comment]
i don't think so
My ollama server is running on that url only. Which is a default url of ollama.

**Comment by ask0ldd** [comment]
Re friend,

Unfortunately, this screenshot proves once more that the issue does not originate from OSspita. 

However, we can still attempt to resolve it. Could you please access this endpoint using Postman? http://localhost:11434/api/tags

Are you running Ollama and this application on the very same machine?

**Comment by ask0ldd** [comment]
Maybe replacing this :

  '/ollama': {
    target: 'http://localhost:11434',
    changeOrigin: true,
    rewrite: (path) => path.replace(/^\/ollama/, '')
  }
  
  With this :
  
  '/ollama': {
    target: 'http://127.0.0.1:11434',
    changeOrigin: true,
    secure: false,
    agent: new https.Agent(),
    rewrite: (path) => path.replace(/^\/ollama/, '')
  }
  
  Could help if the Postman test is a success.

**Comment by RYG81** [comment]
> Re friend,
> 
> Unfortunately, this screenshot proves once more that the issue does not originate from OSspita.
> 
> However, we can still attempt to resolve it. Could you please access this endpoint using Postman? http://localhost:11434/api/tags
> 
> Are you running Ollama and this application on the very same machine?

same machine. and tried change url still same.

**Comment by ask0ldd** [comment]
Thanks a lot for the screenshot.

Honestly, there are two possibilities since Ollama endpoints seem to be accessible through Postman:

1 - Your firewall / antivirus is preventing OSspita from reaching Ollama endpoints.

2 - Some weird behavior is happening when your version of Node tries to resolve localhost... Which should have been solved by replacing localhost with 127.0.0.1

"I see that your version of Node is resolving localhost into an IPv6 loopback address:
Error: connect ECONNREFUSED ::1:11434

I don't really know if that could be part of the issue.

Unfortunately, I have 3 computers with 3 different OSs (Windows, Ubuntu & Mint), and I can't replicate the issue you are facing. That's why I really think the first assertion is the most credible one: firewall / antivirus issue.

My node versions are : 22.11 and 18.19.1

**Comment by RYG81** [comment]
> Thanks a lot for the screenshot.
> 
> Honestly, there are two possibilities since Ollama endpoints seem to be accessible through Postman:
> 
> 1 - Your firewall / antivirus is preventing OSspita from reaching Ollama endpoints.
> 
> 2 - Some weird behavior is happening when your version of Node tries to resolve localhost... Which should have been solved by replacing localhost with 127.0.0.1
> 
> "I see that your version of Node is resolving localhost into an IPv6 loopback address: Error: connect ECONNREFUSED ::1:11434
> 
> I don't really know if that could be part of the issue.
> 
> Unfortunately, I have 3 computers with 3 different OSs (Windows, Ubuntu & Mint), and I can't replicate the issue you are facing. That's why I really think the first assertion is the most credible one: firewall / antivirus issue.
> 
> My node versions are : 22.11 and 18.19.1

At home, I do not have any firewall. So that's not possible. Node version is what you put as required. And if it's changing the ipv4 to ipv6, I think it will be easier for you to fix then me. As I am not a programmer at all.

**Comment by RYG81** [comment]
target: 'http://127.0.0.1:11434', - changing this resolved issue.

not sure why it was not working earlier or may be something is different hen what you suggested.
