### ISSUE TITLE
Trying to connect OSspita to a remote inference server.

### ISSUE THREAD

**Issue by TRYOKETHEPEN** [ask0ldd/OsspitaUI#5]
**My server:**
Ubuntu 20.04, x64
node v23.5.0
ip: 172.18.100.60

**My problem:**
[1] Start as guide, it's OK
[2] But I want to access it from another PC within LAN.
So I changed _Front/package.json_, add "--host 0.0.0.0" to script "dev". 
Restart, visit _172.18.100.60:5173_, ollama model canbe detected, but chat raise error "Error: Stream failed. HTTP error! status: 403"
[3] The error's detail:
![err1](https://github.com/user-attachments/assets/a8128371-d2f1-4024-9786-25f194573a48)
![err2](https://github.com/user-attachments/assets/1aef1f38-e193-4929-9a9f-4b58c486d19e)

I manually POST the same url and payload from the same PC, it's OK.

**Comment by ask0ldd** [comment]
Hi mate!

OSspita wasn't really designed with the use of a distant inference server in mind, as I can't easily streamline the configuration process.

However, here's a hint : This error might be CORS-related.

If it is, you might want to refer to this information:

How can I allow additional web origins to access Ollama?
>> Ollama allows cross-origin requests from 127.0.0.1 and 0.0.0.0 by default. Additional origins can be configured with OLLAMA_ORIGINS.

Perhaps something like this would work:
>> OLLAMA_ORIGINS=frontendUrl ollama serve

Let me know if this helps.

**Comment by TRYOKETHEPEN** [comment]
> Hi mate! And thank you for reaching out!
> 
> OSspita wasn't really designed with the use of a distant inference server in mind, as I can't easily streamline the configuration process.
> 
> However, here's a hint : This error might be CORS-related.
> 
> If it is, you might want to refer to this information:
> 
> How can I allow additional web origins to access Ollama?
> 
> > > Ollama allows cross-origin requests from 127.0.0.1 and 0.0.0.0 by default. Additional origins can be configured with OLLAMA_ORIGINS.
> 
> Perhaps something like this would work:
> 
> > > OLLAMA_ORIGINS=frontendUrl ollama serve
> 
> Let me know if this helps.

Thanks a lot, it did help. (More specific: https://atlassc.net/2024/09/14/how-to-enable-api-for-ollama)

**Comment by ask0ldd** [comment]
Thanks a lot for the link! I'm glad my reply was helpful.

If you need any further assistance, please don't hesitate to ask.
